sources:
  - name: "posts"
    url: "https://jsonplaceholder.typicode.com/posts"
    method: "GET"
    pagination:
      start_page: 1
      end_page: 10
      page_size: 10
      page_param: "page"
      page_size_param: "limit"
      page_size_default: 10
  - name: "comments"
    url: "https://jsonplaceholder.typicode.com/comments"
    method: "GET"
    pagination:
      start_page: 1
      end_page: 10
      page_size: 10
      page_param: "page"
      page_size_param: "limit"
      page_size_default: 10
  - name: "users"
    url: "https://jsonplaceholder.typicode.com/users"
    method: "GET"
    pagination:
      start_page: 1
      end_page: 10
      page_size: 10
      page_param: "page"
      page_size_param: "limit"
      page_size_default: 10
  - name: "albums"
    url: "https://jsonplaceholder.typicode.com/albums"
    method: "GET"
    pagination:
      start_page: 1
      end_page: 10
      page_size: 10
      page_param: "page"
      page_size_param: "limit"
      page_size_default: 10
  - name: "todos"
    url: "https://jsonplaceholder.typicode.com/todos"
    method: "GET"
    pagination:
      start_page: 1
      end_page: 10
      page_size: 10
      page_param: "page"
      page_size_param: "limit"
      page_size_default: 10